### ISSUE TITLE
No print friendly CSS

### ISSUE THREAD

**Issue by lukasni** [5egmegaanon/5etools#10]
Having the ability to print out classes, and to a lesser degree Feats, Spells etc would be convenient for players without a PHB or even for DMs to reference during play. 

The current layout is not very print friendly, especially the class page, since [the div surrounding the #stats table](https://github.com/5egmegaanon/5etools/blob/master/classes.html#L501) has a fixed height set.

I am currently working on a PR to add a basic print template, but wanted to ask about some design decisions, since some changes would likely be necessary.

Mainly this: Most of the CSS is done in-line or with an internal stylesheet. Especially the inline style makes it hard to add a custom print layout without resorting to `@important`, which I would prefer to avoid. Before going on a crusade moving everything to external stylesheets I wanted to ask if there was a good reason for these styles to be inlined.

**Comment by 5egmegaanon** [comment]
The CSS is inline due to poor (read: no) planning on my part. Even the JavaScript was inline, originally. This whole project is largely done by-ear.

The recent update removed most of the inline CSS and I plan on moving the stuff in the <head> tags to a dedicated .css file soon.

I can't say I much care about print CSS, but I can see their use.

**Comment by lukasni** [comment]
I see you already got going on splitting it out in 70e077e, awesome. I'll work something out this weekend, will create the PR then.

**Comment by lukasni** [comment]
I've created some basic print styles in #11 

As stated in the commit, no huge changes, mainly hiding unnecessary stuff in print to avoid pages being too long. Since the default css changed to no longer have a max-height on tables, some of my initial suggested changes are no longer necessary.
