### ISSUE TITLE
Hit point calculations in CR Calculator are incorrect

### ISSUE THREAD

**Issue by rgladwell** [5egmegaanon/5etools#4]
Incorrect calculation: 4d6 should be an effect hit points of (4 * 3.5) = 14 but in CR Calculator this is 16!

Does not add or subtract Cons penalty for effective hit points. For example 2d6 - 2 should be (2 * 3.5 - 2) = 5 but is 6 in CR Calculator!

**Comment by 5egmegaanon** [comment]
Thanks for pointing this out. There were some pretty embarrassing math mistakes in there that should now be fixed.

**Comment by rgladwell** [comment]
Thanks for fixing this so quickly, seems much better.
