### ISSUE TITLE
Challange Rating summary in CR Calculator not always automatically updated

### ISSUE THREAD

**Issue by rgladwell** [5egmegaanon/5etools#5]
Modifying some fields does not automatically update the Challenge Rating summary or recalculate the CR.

For example, raising and lowering the number of hit dice causing the Challenge Rating summary to update the number of hit dice to be one less (i.e setting hit dice to 2 gives you 3d6 in summary0

**Comment by 5egmegaanon** [comment]
There were some problems related to the order CR was calculated in relation to hit dice being calculated, so it was using the _previous_ entry, not the one you just entered. This should be fixed now.
